# Generated by Django 4.2.7 on 2026-04-23 02:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dailyadinsight",
            new_name="reporting_d_meta_ac_d95d72_idx",
            old_name="reporting_d_meta_acct_date",
        ),
    ]
