# Generated by Django 4.2.7 on 2025-09-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adset",
            name="bid_strategy",
            field=models.CharField(
                choices=[
                    ("LOWEST_COST_WITHOUT_CAP", "Lowest Cost Without Cap"),
                    ("LOWEST_COST_WITH_BID_CAP", "Lowest Cost With Bid Cap"),
                    ("COST_CAP", "Cost Cap"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="objective",
            field=models.CharField(
                choices=[
                    ("OUTCOME_TRAFFIC", "Traffic"),
                    ("OUTCOME_CONVERSIONS", "Conversions"),
                    ("OUTCOME_AWARENESS", "Awareness"),
                    ("OUTCOME_ENGAGEMENT", "Engagement"),
                    ("OUTCOME_LEADS", "Leads"),
                    ("OUTCOME_SALES", "Sales"),
                    ("OUTCOME_APP_PROMOTION", "App Promotion"),
                ],
                max_length=50,
            ),
        ),
    ]
