# Generated by Django 4.2.7 on 2025-10-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_adset_bid_strategy_alter_campaign_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='adset',
            name='bid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='adset',
            name='budget_type',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily Budget'), ('LIFETIME', 'Lifetime Budget')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='adset',
            name='delivery_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('ACCELERATED', 'Accelerated')], default='STANDARD', max_length=20),
        ),
        migrations.AddField(
            model_name='adset',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adset',
            name='optimization_goal',
            field=models.CharField(choices=[('NONE', 'None'), ('APP_INSTALLS', 'App Installs'), ('AD_RECALL_LIFT', 'Ad Recall Lift'), ('ENGAGED_USERS', 'Engaged Users'), ('EVENT_RESPONSES', 'Event Responses'), ('IMPRESSIONS', 'Impressions'), ('LEAD_GENERATION', 'Lead Generation'), ('QUALITY_LEAD', 'Quality Lead'), ('LINK_CLICKS', 'Link Clicks'), ('OFFSITE_CONVERSIONS', 'Offsite Conversions'), ('PAGE_LIKES', 'Page Likes'), ('POST_ENGAGEMENT', 'Post Engagement'), ('QUALITY_CALL', 'Quality Call'), ('REACH', 'Reach'), ('LANDING_PAGE_VIEWS', 'Landing Page Views'), ('VISIT_INSTAGRAM_PROFILE', 'Visit Instagram Profile'), ('VALUE', 'Value'), ('THRUPLAY', 'ThruPlay'), ('DERIVED_EVENTS', 'Derived Events')], default='LINK_CLICKS', max_length=50),
        ),
        migrations.AddField(
            model_name='adset',
            name='placement_type',
            field=models.CharField(choices=[('AUTOMATIC', 'Automatic Placements'), ('MANUAL', 'Manual Placements')], default='AUTOMATIC', max_length=20),
        ),
        migrations.AddField(
            model_name='adset',
            name='placements',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='adset',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='budget_optimization',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('ACCELERATED', 'Accelerated')], default='STANDARD', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='budget_remaining',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='schedule_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='schedule_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='schedule_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='timezone',
            field=models.CharField(default='Asia/Tokyo', max_length=50),
        ),
        migrations.AlterField(
            model_name='adset',
            name='bid_strategy',
            field=models.CharField(choices=[('LOWEST_COST_WITHOUT_CAP', 'Lowest Cost Without Cap'), ('LOWEST_COST_WITH_BID_CAP', 'Lowest Cost With Bid Cap'), ('COST_CAP', 'Cost Cap'), ('LOWEST_COST_WITH_MIN_ROAS', 'Lowest Cost With Min ROAS')], default='LOWEST_COST_WITHOUT_CAP', max_length=50),
        ),
        migrations.AlterField(
            model_name='adset',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='budget_type',
            field=models.CharField(choices=[('DAILY', 'Daily Budget'), ('LIFETIME', 'Lifetime Budget')], max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='objective',
            field=models.CharField(choices=[('OUTCOME_AWARENESS', 'Awareness'), ('OUTCOME_BRAND_AWARENESS', 'Brand Awareness'), ('OUTCOME_REACH', 'Reach'), ('OUTCOME_TRAFFIC', 'Traffic'), ('OUTCOME_ENGAGEMENT', 'Engagement'), ('OUTCOME_VIDEO_VIEWS', 'Video Views'), ('OUTCOME_LEAD_GENERATION', 'Lead Generation'), ('OUTCOME_CONVERSIONS', 'Conversions'), ('OUTCOME_SALES', 'Sales'), ('OUTCOME_CATALOG_SALES', 'Catalog Sales'), ('OUTCOME_STORE_VISITS', 'Store Visits'), ('OUTCOME_APP_PROMOTION', 'App Promotion'), ('OUTCOME_APP_INSTALLS', 'App Installs'), ('OUTCOME_MESSAGES', 'Messages'), ('OUTCOME_MESSENGER_ENGAGEMENT', 'Messenger Engagement'), ('OUTCOME_EVENT_RESPONSES', 'Event Responses'), ('OUTCOME_PAGE_LIKES', 'Page Likes'), ('OUTCOME_POST_ENGAGEMENT', 'Post Engagement')], max_length=50),
        ),
    ]
