# Generated by Django 4.2.7 on 2025-10-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_adset_bid_amount_adset_budget_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='creative_type',
            field=models.CharField(choices=[('SINGLE_IMAGE', 'Single Image'), ('SINGLE_VIDEO', 'Single Video'), ('CAROUSEL', 'Carousel'), ('COLLECTION', 'Collection'), ('SLIDESHOW', 'Slideshow'), ('INSTANT_EXPERIENCE', 'Instant Experience')], default='SINGLE_IMAGE', max_length=50),
        ),
        migrations.AddField(
            model_name='ad',
            name='cta_type',
            field=models.CharField(choices=[('NO_BUTTON', 'No Button'), ('LEARN_MORE', 'Learn More'), ('SHOP_NOW', 'Shop Now'), ('SIGN_UP', 'Sign Up'), ('DOWNLOAD', 'Download'), ('BOOK_TRAVEL', 'Book Travel'), ('CONTACT_US', 'Contact Us'), ('GET_QUOTE', 'Get Quote'), ('SUBSCRIBE', 'Subscribe'), ('APPLY_NOW', 'Apply Now'), ('DONATE', 'Donate'), ('GET_OFFER', 'Get Offer'), ('INSTALL_APP', 'Install App'), ('LISTEN_NOW', 'Listen Now'), ('ORDER_NOW', 'Order Now'), ('PLAY_GAME', 'Play Game'), ('REGISTER', 'Register'), ('SEE_MENU', 'See Menu'), ('WATCH_MORE', 'Watch More'), ('SEND_MESSAGE', 'Send Message')], default='LEARN_MORE', max_length=50),
        ),
        migrations.AddField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ad',
            name='display_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ad',
            name='headline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ad',
            name='link_url',
            field=models.URLField(blank=True),
        ),
    ]
