# Generated by Django 4.2.7 on 2025-10-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_ad_creative_type_ad_cta_type_ad_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='facebook_page_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
