# Generated by Django 4.2.7 on 2025-10-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0005_ad_facebook_page_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="objective",
            field=models.CharField(
                choices=[
                    ("APP_INSTALLS", "App Installs"),
                    ("BRAND_AWARENESS", "Brand Awareness"),
                    ("EVENT_RESPONSES", "Event Responses"),
                    ("LEAD_GENERATION", "Lead Generation"),
                    ("LINK_CLICKS", "Link Clicks"),
                    ("LOCAL_AWARENESS", "Local Awareness"),
                    ("MESSAGES", "Messages"),
                    ("OFFER_CLAIMS", "Offer Claims"),
                    ("PAGE_LIKES", "Page Likes"),
                    ("POST_ENGAGEMENT", "Post Engagement"),
                    ("PRODUCT_CATALOG_SALES", "Product Catalog Sales"),
                    ("REACH", "Reach"),
                    ("STORE_VISITS", "Store Visits"),
                    ("VIDEO_VIEWS", "Video Views"),
                    ("OUTCOME_AWARENESS", "Awareness"),
                    ("OUTCOME_ENGAGEMENT", "Engagement"),
                    ("OUTCOME_LEADS", "Leads"),
                    ("OUTCOME_SALES", "Sales"),
                    ("OUTCOME_TRAFFIC", "Traffic"),
                    ("OUTCOME_APP_PROMOTION", "App Promotion"),
                    ("CONVERSIONS", "Conversions"),
                ],
                max_length=50,
            ),
        ),
    ]
