# Generated by Django 4.2.7 on 2025-10-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0006_update_objective_mapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("PAUSED", "Paused"),
                    ("DELETED", "Deleted"),
                ],
                default="PAUSED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="adset",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("PAUSED", "Paused"),
                    ("DELETED", "Deleted"),
                ],
                default="PAUSED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("PAUSED", "Paused"),
                    ("DELETED", "Deleted"),
                ],
                default="PAUSED",
                max_length=20,
            ),
        ),
    ]
