# Generated by Django 4.2.7 on 2025-10-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_alter_ad_status_alter_adset_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='review_feedback',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
