# Generated by Django 4.2.7 on 2025-11-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0008_ad_review_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="cached_insights",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="campaign",
            name="insights_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
