# Generated by Django 4.2.7 on 2025-10-15 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="カテゴリ名")),
                ("name_en", models.CharField(max_length=100, verbose_name="カテゴリ名（英語）")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("description_en", models.TextField(blank=True, verbose_name="説明（英語）")),
                (
                    "icon",
                    models.CharField(
                        default="question-circle", max_length=50, verbose_name="アイコン"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="表示順序")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ヘルプカテゴリ",
                "verbose_name_plural": "ヘルプカテゴリ",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HelpArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                ("title_en", models.CharField(max_length=200, verbose_name="タイトル（英語）")),
                ("content", models.TextField(verbose_name="内容")),
                ("content_en", models.TextField(verbose_name="内容（英語）")),
                (
                    "article_type",
                    models.CharField(
                        choices=[
                            ("text", "テキスト"),
                            ("steps", "ステップガイド"),
                            ("video", "動画ガイド"),
                            ("link", "外部リンク"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="記事タイプ",
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="タグ")),
                ("video_url", models.URLField(blank=True, verbose_name="動画URL")),
                ("external_url", models.URLField(blank=True, verbose_name="外部URL")),
                (
                    "page_context",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ページコンテキスト"
                    ),
                ),
                (
                    "element_selector",
                    models.CharField(blank=True, max_length=200, verbose_name="要素セレクタ"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="表示順序")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="おすすめ"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="閲覧数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="help.helpcategory",
                        verbose_name="カテゴリ",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
            options={
                "verbose_name": "ヘルプ記事",
                "verbose_name_plural": "ヘルプ記事",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="UserGuideProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guide_type", models.CharField(max_length=50, verbose_name="ガイドタイプ")),
                (
                    "completed_steps",
                    models.JSONField(default=list, verbose_name="完了したステップ"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="完了済み"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完了日時"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guide_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザーガイド進捗",
                "verbose_name_plural": "ユーザーガイド進捗",
                "unique_together": {("user", "guide_type")},
            },
        ),
        migrations.CreateModel(
            name="HelpFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "とても役に立たなかった"),
                            (2, "役に立たなかった"),
                            (3, "普通"),
                            (4, "役に立った"),
                            (5, "とても役に立った"),
                        ],
                        verbose_name="評価",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="コメント")),
                ("is_helpful", models.BooleanField(default=True, verbose_name="役に立った")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="help.helparticle",
                        verbose_name="記事",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ヘルプフィードバック",
                "verbose_name_plural": "ヘルプフィードバック",
                "unique_together": {("article", "user")},
            },
        ),
    ]
