# Generated by Django 4.2.7 on 2025-10-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("help", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="helparticle",
            name="summary",
            field=models.TextField(
                default="", help_text="一覧表示用の短い説明文", verbose_name="要約"
            ),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="summary_en",
            field=models.TextField(
                default="", help_text="一覧表示用の短い説明文（英語）", verbose_name="要約（英語）"
            ),
        ),
    ]
