# Generated by Django 4.2.7 on 2025-10-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("help", "0002_helparticle_summary_helparticle_summary_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="helparticle",
            name="content_ko",
            field=models.TextField(default="", verbose_name="内容（韓国語）"),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="content_zh",
            field=models.TextField(default="", verbose_name="内容（中国語）"),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="summary_ko",
            field=models.TextField(
                default="", help_text="一覧表示用の短い説明文（韓国語）", verbose_name="要約（韓国語）"
            ),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="summary_zh",
            field=models.TextField(
                default="", help_text="一覧表示用の短い説明文（中国語）", verbose_name="要約（中国語）"
            ),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="title_ko",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="タイトル（韓国語）"
            ),
        ),
        migrations.AddField(
            model_name="helparticle",
            name="title_zh",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="タイトル（中国語）"
            ),
        ),
    ]
