# Generated by Django 4.2.7 on 2025-10-07 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0007_alter_ad_status_alter_adset_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_notifications_enabled', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='通知停止開始時間', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='通知停止終了時間', null=True)),
                ('default_chatwork_webhook', models.URLField(blank=True, help_text='デフォルトChatwork Webhook URL')),
                ('default_slack_webhook', models.URLField(blank=True, help_text='デフォルトSlack Webhook URL')),
                ('default_email', models.EmailField(blank=True, help_text='デフォルト通知メールアドレス', max_length=254)),
                ('max_notifications_per_hour', models.IntegerField(default=10, help_text='時間あたりの最大通知数')),
                ('max_notifications_per_day', models.IntegerField(default=50, help_text='日あたりの最大通知数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Settings',
                'verbose_name_plural': 'Alert Settings',
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='アラートルール名', max_length=200)),
                ('description', models.TextField(blank=True, help_text='アラートルールの説明')),
                ('alert_type', models.CharField(choices=[('BUDGET_THRESHOLD', 'Budget Threshold'), ('PERFORMANCE_DROP', 'Performance Drop'), ('CAMPAIGN_PAUSED', 'Campaign Paused'), ('API_ERROR', 'API Error'), ('BULK_UPLOAD_COMPLETE', 'Bulk Upload Complete'), ('BULK_UPLOAD_FAILED', 'Bulk Upload Failed'), ('CUSTOM', 'Custom')], max_length=50)),
                ('condition', models.CharField(choices=[('GREATER_THAN', 'Greater Than'), ('LESS_THAN', 'Less Than'), ('EQUALS', 'Equals'), ('NOT_EQUALS', 'Not Equals'), ('CONTAINS', 'Contains')], max_length=20)),
                ('threshold_value', models.CharField(help_text='閾値（数値、文字列、パーセンテージなど）', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_frequency', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='IMMEDIATE', max_length=20)),
                ('chatwork_webhook_url', models.URLField(blank=True, help_text='Chatwork Webhook URL')),
                ('slack_webhook_url', models.URLField(blank=True, help_text='Slack Webhook URL')),
                ('email_notification', models.BooleanField(default=False)),
                ('chatwork_message_template', models.TextField(default='🚨 アラート: {alert_name}\n📊 キャンペーン: {campaign_name}\n📈 値: {current_value}\n🎯 閾値: {threshold_value}', help_text='Chatworkメッセージテンプレート')),
                ('slack_message_template', models.TextField(default='🚨 *アラート: {alert_name}*\n📊 *キャンペーン:* {campaign_name}\n📈 *値:* {current_value}\n🎯 *閾値:* {threshold_value}', help_text='Slackメッセージテンプレート')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('target_campaigns', models.ManyToManyField(blank=True, help_text='対象キャンペーン（空の場合は全キャンペーン）', to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('current_value', models.CharField(help_text='現在の値', max_length=100)),
                ('threshold_value', models.CharField(help_text='閾値', max_length=100)),
                ('channel', models.CharField(choices=[('CHATWORK', 'Chatwork'), ('SLACK', 'Slack'), ('EMAIL', 'Email'), ('DASHBOARD', 'Dashboard')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='エラーメッセージ')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('response_data', models.JSONField(default=dict, help_text='送信レスポンスデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.alertrule')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Alert Notification',
                'verbose_name_plural': 'Alert Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
