# Generated by Django 4.2.7 on 2025-10-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='email_addresses',
            field=models.TextField(blank=True, help_text='通知先メールアドレス（複数の場合は改行区切り）'),
        ),
    ]
