# Generated by Django 4.2.7 on 2025-10-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_upload", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkupload",
            name="selected_account_id",
            field=models.IntegerField(
                blank=True, help_text="選択されたMetaアカウントID", null=True
            ),
        ),
    ]
