# Generated by Django 4.2.7 on 2025-10-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="backup_codes",
            field=models.TextField(blank=True, verbose_name="backup codes"),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_enabled",
            field=models.BooleanField(default=False, verbose_name="2FA enabled"),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_secret",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="2FA secret"
            ),
        ),
    ]
