# Generated by Django 4.2.7 on 2025-10-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_backup_codes_user_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meta_app_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Meta App ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='meta_app_secret',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta App Secret'),
        ),
    ]
