# Generated by Django 4.2.7 on 2025-10-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_meta_app_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meta_app_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Meta App ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='meta_app_secret',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta App Secret'),
        ),
    ]
