# Generated by Django 4.2.7 on 2025-10-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_meta_app_id_user_meta_app_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='meta_app_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='meta_app_secret',
        ),
    ]
