# Generated by Django 4.2.7 on 2025-11-18 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_user_meta_app_id_remove_user_meta_app_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoxAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(max_length=100)),
                ("account_name", models.CharField(max_length=200)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="box_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Box Account",
                "verbose_name_plural": "Box Accounts",
                "unique_together": {("user", "account_id")},
            },
        ),
    ]
