# Generated by Django 4.2.7 on 2026-04-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_boxaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="metaaccount",
            name="business_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="metaaccount",
            name="business_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
